# Generated by Django 4.1.5 on 2023-01-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='discription',
            field=models.TextField(max_length=255),
        ),
    ]
