# Generated by Django 4.1.5 on 2023-01-25 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meet', '0002_alter_questionnaire_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='discription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
